image: python:3.10-bullseye
command: |
    mkdir -p .venv
    python -m venv .venv
    . .venv/bin/activate

    pip install -q -r requirements.pip.dev.txt

    apt-get -qqq update
    apt-get -qqq install socat

    doit check
    doit test
